# For more information, please refer to deployment documentation: https://github.com/finos/symphony-wdk/blob/master/docs/deployment.md
bdk:
  host: develop2.symphony.com
  bot:
    username: WDKBot
    privateKey:
      path: rsa/privatekey.pem
